hariduspilv/haridusportaal

drupal/web/modules/custom/htm_custom_admin_form/config/install/htm_custom_admin_form.customadmin.yml, drupal/web/modules/custom/htm_custom_admin_form/config/schema/htm_custom_admin_form.schema.yml, drupal/web/modules/custom/htm_custom_admin_form/htm_custom_admin_form.config_translation.yml, drupal/web/modules/custom/htm_custom_admin_form/htm_custom_admin_form.info.yml, drupal/web/modules/custom/htm_custom_admin_form/htm_custom_admin_form.links.menu.yml, drupal/web/modules/custom/htm_custom_admin_form/htm_custom_admin_form.links.task.yml, drupal/web/modules/custom/htm_custom_admin_form/htm_custom_admin_form.routing.yml, drupal/web/modules/custom/htm_custom_admin_form/src/Form/CustomAdminForm.php, drupal/web/modules/custom/htm_custom_event_registration/htm_custom_event_registration.module, drupal/web/modules/custom/htm_custom_event_registration/src/Entity/EventRegEntity.php, drupal/web/modules/custom/htm_custom_tokens/htm_custom_tokens.info.yml, drupal/web/modules/custom/htm_custom_tokens/htm_custom_tokens.module
=> Admin form

angular2/src/app/_views/xjson/xjson.component.ts, angular2/src/app/_views/xjson/xjson.styles.scss, angular2/src/app/_views/xjson/xjson.template.html
File label text size to 16.
Larger margin between table and field.
File upload validation error vanishes after correct file has been uploaded.
=> xjson design improvements

angular-fe/src/app/_assets/header/header.template.html, angular-fe/src/app/_services/SidemenuService.ts, angular-fe/stories/assets/sidemenu/sidemenu.stories.ts, angular-fe/stories/layouts/base/base.stories.ts
Sidemenu service is now singleton
Header button toggles sidemenu
=> fixed sidemenu and header stories

angular-fe/src/app/_assets/article-layout/article.layout.styles.scss, angular-fe/src/app/_assets/header/header.styles.scss, angular-fe/src/app/_assets/header/header.template.html, angular-fe/src/app/_assets/sidebar/sidebar.styles.scss, angular-fe/stories/assets/sidebar/sidebar.data.ts
=> Fe refactor header desktop

angular-fe/src/app/_assets/index.ts, angular-fe/src/app/_assets/labels/index.ts, angular-fe/src/app/_assets/labels/labels.component.ts, angular-fe/src/app/_assets/labels/labels.styles.scss, angular-fe/src/app/_assets/labels/labels.template.html, angular-fe/stories/assets/labels/labels.md, angular-fe/stories/assets/labels/labels.stories.ts
=> Labels component #HP-228

angular-fe/src/app/_assets/index.ts, angular-fe/src/app/_assets/labeled-separator/index.ts, angular-fe/src/app/_assets/labeled-separator/labeled.separator.component.ts, angular-fe/src/app/_assets/labeled-separator/labeled.separator.styles.scss, angular-fe/src/app/_assets/labeled-separator/labeled.separator.template.html, angular-fe/stories/assets/labeledSeparator/labeledSeparator.md, angular-fe/stories/assets/labeledSeparator/labeledSeparator.stories.ts
=> Fe refactor labeled separator

angular-fe/src/app/_assets/share/share.component.ts, angular-fe/stories/assets/share/share.html
=> Share alert update

angular-fe/src/app/_assets/sidebar/sidebar.styles.scss, angular-fe/src/app/_assets/sidebar/templates/sidebar.notifications.template.html, angular-fe/src/app/_core/conf.ts, angular-fe/src/app/_interceptors/auth.interceptors.ts, angular-fe/src/app/_services/AuthService.ts, angular-fe/src/app/_views/dashboardView/dashboard.component.ts, angular-fe/src/app/_views/dashboardView/dashboard.styles.scss, angular-fe/src/app/_views/documentCheckView/documentCheck.component.ts, angular-fe/src/app/_views/documentCheckView/documentCheck.styles.scss, angular-fe/src/app/_views/documentCheckView/documentCheck.template.html, angular-fe/src/app/_views/documentCheckView/index.ts, angular-fe/src/app/_views/messagesView/index.ts, angular-fe/src/app/_views/messagesView/messageView/messageView.component.ts, angular-fe/src/app/_views/messagesView/messageView/messageView.styles.scss, angular-fe/src/app/_views/messagesView/messageView/messageView.template.html, angular-fe/src/app/_views/messagesView/messagesView.component.ts, angular-fe/src/app/_views/messagesView/messagesView.styles.scss, angular-fe/src/app/_views/messagesView/messagesView.template.html, angular-fe/src/app/app.routes.ts, angular-fe/src/app/scss/colors.scss
=> EHIS2 teavitused + EHIS2 lõpudokumentide kontroll

angular-fe/src/app/_assets/modal/modal.component.ts, angular-fe/src/app/_assets/modal/modal.template.html, angular-fe/src/app/_assets/sessionExpiration/sessionExpiration.component.ts, angular-fe/src/app/_assets/sessionExpiration/sessionExpiration.template.html, angular-fe/src/app/_pipes/ellipsis.pipe.ts, angular-fe/src/app/_services/ModalService.ts
https://jira.twn.ee/browse/HP-392
=> Sprint 47 hp 392

angular-fe/src/app/_assets/accordion/accordion-item.template.html, angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.template.html, angular-fe/src/app/_assets/feedback/feedback.component.ts, angular-fe/src/app/_assets/feedback/feedback.template.html, angular-fe/tslint.json
https://jira.twn.ee/browse/HP-265
=> Sprint 47 hp 265

angular-fe/src/app/_assets/header/header.styles.scss, angular-fe/src/app/_assets/header/header.template.html, angular-fe/src/app/_assets/index.ts, angular-fe/src/app/_assets/menu/sidemenu.component.ts, angular-fe/src/app/_assets/menu/sidemenu.item.template.html, angular-fe/src/app/_assets/menu/sidemenu.styles.scss, angular-fe/src/app/_assets/menu/sidemenu.template.html, angular-fe/src/app/app.component.html, angular-fe/src/app/app.component.scss, angular-fe/src/app/scss/colors.scss
Peamenüü ümberkujundus: toetab kolmetasemelist struktuuri, nagu nõutud. Nõuab backist peamenüü muutmist, kuna nüüd on kõige esimene link menüüpuus kategooria.
Ehk on soovi kuidagi teha menüü värvid BE kaudu? Praegu on staatiliselt kategooria slugi järgi pandud värv, mis ühtib teemadega. Värvid võtsin kujundustest.
=> Sprint 53 hp 594

drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaTableEntity.php, drupal/web/modules/custom/htm_custom_oska/src/Form/OskaTableImportDataForm.php, drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaTableData.php
Field for status color added in drupal- both in csv import and table field input
=> Sprint 54 hp 532

angular-fe/src/app/_views/detailView/detailView.component.ts, angular-fe/src/app/_views/detailView/detailView.template.html
Continues #1281 to the front-end.
=> HP-549 (FE) | Eelvaate parandused

angular-fe/src/app/_assets/sidebar/sidebar.component.ts
=> HP-544 (FE) | Ametiala vaatest tühjade valdkondade eemaldamine 

angular-fe/ngsw-config.json, angular-fe/package-lock.json, angular-fe/package.json, angular-fe/src/app/_assets/index.ts, angular-fe/src/app/_assets/sidebar/helpers/sidebar.ts, angular-fe/src/app/_assets/sidebar/models/certificate-owner.ts, angular-fe/src/app/_assets/sidebar/models/final-document-download-sidebar.ts, angular-fe/src/app/_assets/sidebar/sidebar.component.ts, angular-fe/src/app/_assets/sidebar/templates/sidebar.finaldocument-history.template.html, angular-fe/src/app/modules/certificates/certificates.utility.ts, angular-fe/src/app/modules/certificates/containers/final-document-dashboard-detail/final-document-dashboard-detail.component.ts, angular-fe/src/app/modules/certificates/models/interfaces/certificate-document.ts, angular-fe/src/app/modules/certificates/models/interfaces/certificate-final-document-dashboard-sidebar.ts
=> Hp release 1 55 6

angular-fe/src/app/_assets/notFound/notFound.template.html
Added translations:
-  notFound.explanation_string
-  notFound.auth_explanation_string
=> HP-572 - improve 404 page button aria-labels

angular-fe/src/app/_assets/menu/sidemenu-item.component.ts, angular-fe/src/app/_assets/menu/sidemenu.component.ts
do not expand all third level options, second level sub menus work as accordions, open the menu when clicking to a content page from a home page.
=> HP-727 + HP-728 | menu changes

drupal/config/sync/language.content_settings.taxonomy_term.publicationlanguage.yml, drupal/config/sync/language.content_settings.taxonomy_term.publicationtype.yml, drupal/config/sync/language.content_settings.taxonomy_term.studylabel.yml, drupal/config/sync/language.content_settings.taxonomy_term.studytag.yml, drupal/config/sync/taxonomy.vocabulary.publicationlanguage.yml, drupal/config/sync/taxonomy.vocabulary.publicationtype.yml, drupal/config/sync/taxonomy.vocabulary.studylabel.yml, drupal/config/sync/taxonomy.vocabulary.studytag.yml
Study taxonomy added for PublicationLanguage, PublicationType, StudyLabel & StudyTag
=> Sprint 55 hp 715

docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_LOPETAMINE_TAOTLUS.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_MUUTMINE_TAOTLUS.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_SULGEMINE_TAOTLUS.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_TAOTLUS.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSNAITAJAD.json, docs/xjson_definitsioonid/MTSYS_TEGEVUSNAITAJAD_ARUANNE.json, docs/xjson_definitsioonid/OLT_OTSUS.json, docs/xjson_definitsioonid/OLT_TAOTLUS.json, docs/xjson_definitsioonid/VPT_ESITATUD_TAOTLUS.json, docs/xjson_definitsioonid/VPT_ESITATUD_TAOTLUS_OTSUS.json, docs/xjson_definitsioonid/VPT_TAOTLUS.json, drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/xJsonSchema.json, drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php
Add helpertext to OLT_TAOTLUS and VPT_TAOTLUS xjson body.
Fix typo in xJsonService.php file comment.
Add existing xjson definitions to docs folder
=> OLT-157 | Add helpertext field to xjson schema.

angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.styles.scss, angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.template.html
Screen readers did not read last element correctly
=> HP-579 - improve breadcrumbs accessibility

angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html, angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.scss, angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.ts, angular-fe/src/app/modules/study/models/mapped-study-page.ts, angular-fe/src/app/modules/study/study-utility.ts
HP-729 Corrections after testing ( method join() went from html to utility )
=> HP-729 corrections after testing ( join() from html to utility )

angular-fe/src/app/_views/oskaFieldMap/oskaFieldMap.component.ts, angular-fe/src/app/_views/oskaFieldMap/oskaFieldMap.template.html, angular-fe/src/app/_views/schoolListView/map/schoolListMap.component.ts, angular-fe/src/app/_views/schoolListView/map/schoolListMap.template.html
nasty approach, only way it seems to work
=> hide map from assistive technologies

drupal/composer.json, drupal/composer.lock
Tuum viidud 8.9.15 pealt 8.9.16 peale, Conditional Fields & CTools uuendatud
=> HP-864 | Drupali turvauuendused

drupal/composer.json, drupal/composer.lock, drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaStudiesData.php
Drupal security update and study programme csv import error message updated
=> Hp release 2 10 4

drupal/docker/prod/run.sh
/logs & /php  subfolder permission changes (previously were 500) and /files folder & its subfolder user change command fixed
=> HP-857 | /files subfolder changes in run.sh

drupal/docker/prod/run.sh, drupal/web/modules/custom/htm_custom_tara_authentication/src/Plugin/OpenIDConnectClient/Tara.php
Tara authorization error fixed
Drupal logs subfolder permissions fixed
=> Hp release 2 10 6

drupal/composer.json, drupal/composer.lock
OpenID Connect security update
=> Hp 882 | OpenID Connect security update

angular-fe/src/app/modules/certificates/components/certificate-detailed/certificate-detailed.component.html
finaldocuments.date_of translation changed
=> ETUN-267 | certificate view changes

drupal/web/modules/custom/htm_custom_ehis_connector/src/EhisConnectorService.php
Isikukaart (eeIsikukaart) request split into different parts, according to which tab is open.
This pull request also contains solutions for tickets HP-707, HP-635 and HP-633 + added EeIsikukaartGDPR tab.
=> Hp 630 - Isikukaart request changed

drupal/composer.json, drupal/composer.lock
'field defaults' update also appears in this PR but it already exists in the develop branch
=> HP-898 | Drupal core updated to 8.9.17

drupal/web/modules/custom/htm_custom_file_logging/src/WriteService.php
If a file exists in /logs/directory and its user:group is not apache then change it to apache
=> HP-874 | watchdog logs error fix 3.0

angular-fe/src/app/_assets/searchResults/searchResults.component.ts, angular-fe/src/app/_assets/sidebar/sidebar.component.ts, angular-fe/src/app/_assets/sidebar/sidebar.template.html, angular-fe/src/app/_assets/sidebar/templates/sidebar.contact.template.html, angular-fe/src/app/_assets/table/studyProgramme.parser.ts, angular-fe/src/app/_views/detailView/detailView.component.ts, angular-fe/src/app/_views/homeSearchListView/homeSearchListView.component.ts, angular-fe/src/app/_views/homeSearchListView/homeSearchListView.template.html, angular-fe/src/app/_views/schoolListView/schoolListView.component.ts
https://jira.twn.ee/browse/HP-929
=> HP-929-fixed search results after updates of elastic search' types names change

angular-fe/src/app/_assets/sidebar/sidebar.component.ts, angular-fe/src/app/_assets/sidebar/sidebar.template.html, angular-fe/src/app/_assets/sidebar/templates/sidebar.contact.template.html, angular-fe/src/app/_assets/table/studyProgramme.parser.ts
https://jira.twn.ee/browse/HP-928
=> HP-928 study programm detail view changes

angular-fe/src/app/_assets/listItem/listItem.template.html, angular-fe/src/app/_assets/searchResults/searchResults.component.ts, angular-fe/src/app/_assets/searchResults/searchResults.template.html, angular-fe/src/app/_services/FieldVaryService.ts, angular-fe/src/app/_views/studyProgrammeListView/studyProgrammeListView.component.ts, angular-fe/src/app/_views/studyProgrammeListView/studyProgrammeListView.template.html
https://jira.twn.ee/browse/HP-927
=> HP-927 - eliminated search of the programs with only open admission

angular-fe/src/app/_assets/header/header.component.ts, angular-fe/src/app/_assets/header/header.styles.scss
HP-1024 - fixed: hamburger-button surrounded with border after closing sidemenu on mobile or tablet view
https://jira.twn.ee/browse/HP-1024
=> HP-1024 - fixed: hamburger-button surrounded with border

angular-fe/src/app/_assets/header/header.component.ts, angular-fe/src/app/_assets/header/header.styles.scss
Reverts hariduspilv/haridusportaal#1757
=> Revert "HP-1024 - fixed: hamburger-button surrounded with border"

angular-fe/src/app/_assets/article-layout/article.layout.component.ts, angular-fe/src/app/_assets/sidebar/helpers/sidebar.ts, angular-fe/src/app/_assets/sidebar/sidebar.component.ts, angular-fe/src/app/_views/detailView/detailView.template.html
[…ofession block title and realized learning opportunities filters for Profession)](https://jira.twn.ee/browse/HP-1006
https://jira.twn.ee/browse/HP-1007)
=> HP-1007 - FE: Ameti ja ametiala sidumine

angular-fe/src/app/_assets/header/dropdown-menu/dropdown-menu.component.html, angular-fe/src/app/_assets/header/dropdown-menu/dropdown-menu.component.scss, angular-fe/src/app/_assets/header/dropdown-menu/dropdown-menu.component.ts, angular-fe/src/app/_assets/header/header.component.ts, angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts, angular-fe/src/app/_assets/notFound/notFound.component.ts, angular-fe/src/app/_assets/notFound/notFound.template.html, angular-fe/src/app/_assets/searchResults/searchResults.component.ts, angular-fe/src/app/_assets/sidebar/templates/sidebar.events.template.html, angular-fe/src/app/_assets/sidebar/templates/sidebar.gdpr.template.html, angular-fe/src/app/_assets/sidebar/templates/sidebar.notifications.template.html, angular-fe/src/app/_assets/studies/studies.template.html, angular-fe/src/app/_assets/teachings/teachings.template.html, angular-fe/src/app/_core/router-dictionary.ts, angular-fe/src/app/_views/detailView/detailView.component.ts, angular-fe/src/app/_views/detailView/detailView.template.html, angular-fe/src/app/_views/gdprView/gdprView.template.html, angular-fe/src/app/_views/homePageView/components/homepage-navblock/homePageView.navblock.html, angular-fe/src/app/_views/messagesView/messageView/messageView.template.html, angular-fe/src/app/_views/messagesView/messagesView.template.html, angular-fe/src/app/_views/schoolFunding/schoolFundingView.component.ts, angular-fe/src/app/_views/schoolListView/schoolListView.component.ts, angular-fe/src/app/_views/studyProgrammeListView/studyProgrammeListView.component.ts, angular-fe/src/app/modules/certificates/components/certificate-final-documents/certificate-final-documents.component.html, angular-fe/src/app/modules/certificates/containers/certificates-detail/certificates-detail.component.html, angular-fe/src/app/modules/study/containers/study-list/study-list.component.ts, angular-fe/src/app/modules/study/study-utility.ts
https://jira.twn.ee/browse/HP-1004
=> HP-1004 - fixed bugs described in the first comment of the ticket

angular-fe/src/app/_assets/header/header.template.html
Removed style="display: none;" for prelive
=> HP-1108 | FE: Keelevahetuse Feature flag; rm display none

angular-fe/Dockerfile, angular-fe/Dockerfile.prelive, angular-fe/Dockerfile.prod, drupal/docker/prod/Dockerfile
python2 to python update fix in docker files (project build shows error)
=> python2 to python update fix in docker files (project build shows error)

angular-fe/Dockerfile, angular-fe/Dockerfile.prelive, angular-fe/Dockerfile.prod, drupal/docker/prod/Dockerfile
Reverts hariduspilv/haridusportaal#1827
=> Revert "python2 to python update fix in docker files (project build shows error)"

angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.component.ts, angular-fe/src/app/_assets/eventsList/eventsList.component.ts, angular-fe/src/app/_assets/header/header.component.ts, angular-fe/src/app/_assets/header/header.template.html, angular-fe/src/app/_core/router-dictionary.ts, angular-fe/src/app/_core/router-utility.ts, angular-fe/src/app/_views/eventsView/eventsView.component.ts, angular-fe/src/app/_views/homeSearchListView/homeSearchListView.component.ts, angular-fe/src/app/_views/homeSearchListView/homeSearchListView.template.html, angular-fe/src/app/_views/oskaFrontpageView/oskaFrontpageView.component.html, angular-fe/src/app/_views/schoolFunding/areas/schoolFundingAreasView.component.ts, angular-fe/src/app/app.routes.ts, angular-fe/src/app/modules/certificates/containers/certificates-dashboard-detail/certificates-dashboard-detail.component.html
Parandatud jäljerida/leivapuru/breadcrumbs seal, kus komponendi render käib angularis.
Pealehe otsing tehtud mitmekeelseks.
=> HP-1132 - FE: otsingud mitmekeelseks

angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.html, angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.ts, angular-fe/src/app/modules/youth-monitoring/containers/youth-monitoring-list/youth-monitoring-list.component.html, angular-fe/src/app/modules/youth-monitoring/models/interfaces.ts, angular-fe/src/app/modules/youth-monitoring/youth-monitoring-utility.ts
Reverts hariduspilv/haridusportaal#1867
=> Revert "HP-1184 changes"
